apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dls-be-hpa-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dls-be-deployment-dev
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70